"""
Tests for src/agents/checkpoint_utils.py

Verifies:
- save_agent_checkpoint with custom folder name
- save_agent_checkpoint with auto-generated name (backward compatibility)
- Error handling for duplicate folder names
- Edge cases for custom folder names
"""

import pytest
from pathlib import Path
from unittest.mock import Mock


@pytest.fixture
def mock_checkpointable_agent():
    """Mock agent that implements CheckpointableAgent."""
    agent = Mock()
    agent.to_checkpoint = Mock()
    return agent


@pytest.fixture
def mock_config():
    """Mock config with minimal required fields."""
    config = Mock(spec=['device', 'num_sims'])
    config.device = 'cpu'
    config.num_sims = 100
    return config


@pytest.fixture
def temp_root_dir(tmp_path):
    """Temporary root directory for checkpoint tests."""
    return tmp_path / "saved_agents"


class TestSaveAgentCheckpoint:
    """Tests for save_agent_checkpoint custom folder naming."""

    def test_custom_folder_name_creates_directory(
        self, mock_checkpointable_agent, mock_config, temp_root_dir
    ):
        """Custom folder name should create directory with that exact name."""
        from src.agents.checkpoint_utils import save_agent_checkpoint

        save_dir = save_agent_checkpoint(
            agent=mock_checkpointable_agent,
            agent_class_name="MCGSAgent",
            game_name="tictactoe",
            config=mock_config,
            root_dir=str(temp_root_dir),
            custom_folder_name="my_agent_v1"
        )

        assert save_dir == temp_root_dir / "my_agent_v1"
        assert save_dir.exists()
        assert (save_dir / "agent.yaml").exists()

    def test_custom_folder_name_raises_if_exists(
        self, mock_checkpointable_agent, mock_config, temp_root_dir
    ):
        """Custom folder name should raise FileExistsError if directory exists."""
        from src.agents.checkpoint_utils import save_agent_checkpoint

        existing_dir = temp_root_dir / "existing_agent"
        existing_dir.mkdir(parents=True)

        with pytest.raises(FileExistsError, match="already exists"):
            save_agent_checkpoint(
                agent=mock_checkpointable_agent,
                agent_class_name="MCGSAgent",
                game_name="tictactoe",
                config=mock_config,
                root_dir=str(temp_root_dir),
                custom_folder_name="existing_agent"
            )

    @pytest.mark.parametrize("empty_value", [None, "", "   "])
    def test_empty_or_none_uses_autogenerated(
        self, mock_checkpointable_agent, mock_config, temp_root_dir, empty_value
    ):
        """None, empty string, or whitespace falls back to auto-generated name."""
        from src.agents.checkpoint_utils import save_agent_checkpoint

        save_dir = save_agent_checkpoint(
            agent=mock_checkpointable_agent,
            agent_class_name="MCGSAgent",
            game_name="tictactoe",
            config=mock_config,
            root_dir=str(temp_root_dir),
            custom_folder_name=empty_value
        )

        folder_name = save_dir.name
        assert "tictactoe" in folder_name
        assert "MCGSAgent" in folder_name
        assert folder_name[:8].isdigit()  # YYYYMMDD timestamp

    @pytest.mark.parametrize("invalid_name", ["subdir/agent", "subdir\\agent"])
    def test_path_separator_raises(
        self, mock_checkpointable_agent, mock_config, temp_root_dir, invalid_name
    ):
        """Path separators (/ or \\) in custom name should raise ValueError."""
        from src.agents.checkpoint_utils import save_agent_checkpoint

        with pytest.raises(ValueError, match="path separator"):
            save_agent_checkpoint(
                agent=mock_checkpointable_agent,
                agent_class_name="MCGSAgent",
                game_name="tictactoe",
                config=mock_config,
                root_dir=str(temp_root_dir),
                custom_folder_name=invalid_name
            )

    def test_whitespace_stripped(
        self, mock_checkpointable_agent, mock_config, temp_root_dir
    ):
        """Leading/trailing whitespace should be stripped from custom name."""
        from src.agents.checkpoint_utils import save_agent_checkpoint

        save_dir = save_agent_checkpoint(
            agent=mock_checkpointable_agent,
            agent_class_name="MCGSAgent",
            game_name="tictactoe",
            config=mock_config,
            root_dir=str(temp_root_dir),
            custom_folder_name="  my_agent  "
        )

        assert save_dir.name == "my_agent"

    def test_to_dict_used_for_config_serialization(
        self, mock_checkpointable_agent, temp_root_dir
    ):
        """Config with to_dict() should serialize algorithm config correctly."""
        import yaml
        from src.agents.checkpoint_utils import save_agent_checkpoint

        # Create config with to_dict() returning nested structure
        # Use spec to restrict which attributes exist
        config = Mock(spec=['device', 'to_dict'])
        config.device = 'cpu'
        config.to_dict = Mock(return_value={
            'mcgs': {'num_sims': 500, 'c_exploration': 1.5},
            'device': 'cpu'
        })

        save_dir = save_agent_checkpoint(
            agent=mock_checkpointable_agent,
            agent_class_name="MCGSAgent",
            game_name="tictactoe",
            config=config,
            root_dir=str(temp_root_dir),
            custom_folder_name="test_to_dict"
        )

        # Verify to_dict was called
        config.to_dict.assert_called_once()

        # Verify saved YAML has correct structure
        with (save_dir / "agent.yaml").open() as f:
            saved = yaml.safe_load(f)

        assert 'mcgs' in saved
        assert saved['mcgs']['num_sims'] == 500
        assert saved['mcgs']['c_exploration'] == 1.5
