# Train AlphaZero on TicTacToe (Full ~30-60 min)
# Usage: cp scripts/samples/train_tictactoe_alphazero_full.yaml scripts/train.yaml && python scripts/train.py
# Full training - produces a strong agent

game: tictactoe

algorithm:
  name: alphazero
  device: mps

  model:
    class: TicTacToeMLPNet
    hidden: 128

  iterations: 400
  games_per_iteration: 25
  batch_size: 128
  train_steps_per_iteration: 200
  lr: 0.001
  weight_decay: 0.0001
  value_loss_coef: 1.0

  temp_moves: 6
  tau: 1.0
  deterministic_after_temp: true
  add_dirichlet_noise: true

  num_sims: 200
  c_puct: 1.5
  dirichlet_alpha: 0.3
  dirichlet_eps: 0.25
  illegal_action_penalty: 1000000000.0

  buffer_capacity: 100000
  clear_mcts_each_game: true
