# Validate Vanilla MCTS on TicTacToe
# Usage: cp scripts/samples/train_tictactoe_vanilla_mcts.yaml scripts/train.yaml && python scripts/train.py
# Note: Vanilla MCTS has no training - this just validates the implementation

game: tictactoe

algorithm:
  name: vanilla_mcts

  # Validation settings
  num_test_games: 10
  random_seed: 42
  verbose: true

  # MCTS settings
  num_sims: 500
  c_exploration: 1.414  # sqrt(2) is theoretically optimal for UCB1
  max_rollout_depth: 50
  rollout_seed: 42
  illegal_action_penalty: 1000000000.0
