# Train AlphaZero on Connect4 (Quick ~10-15 min)
# Usage: cp scripts/samples/train_connect4_alphazero_quick.yaml scripts/train.yaml && python scripts/train.py
# Quick settings - weak agent but fast training for testing

game: connect4

algorithm:
  name: alphazero
  device: cpu

  model:
    class: Connect4MLPNet
    hidden: 128

  iterations: 50
  games_per_iteration: 8
  batch_size: 64
  train_steps_per_iteration: 50
  lr: 0.003
  weight_decay: 0.0001
  value_loss_coef: 1.0

  temp_moves: 8
  tau: 1.0
  deterministic_after_temp: true
  add_dirichlet_noise: true

  num_sims: 50
  c_puct: 1.25
  dirichlet_alpha: 0.4
  dirichlet_eps: 0.2
  illegal_action_penalty: 1000000000.0

  buffer_capacity: 50000
  clear_mcts_each_game: true
