# Validate Vanilla MCTS on Connect4
# Usage: cp scripts/samples/train_connect4_vanilla_mcts.yaml scripts/train.yaml && python scripts/train.py
# Note: Vanilla MCTS has no training - this just validates the implementation

game: connect4

algorithm:
  name: vanilla_mcts

  num_test_games: 10
  random_seed: 42
  verbose: true

  num_sims: 1000
  c_exploration: 1.414
  max_rollout_depth: 100
  rollout_seed: 42
  illegal_action_penalty: 1000000000.0
