# Train AlphaZero on Connect4 (Full ~2-4 hours)
# Usage: cp scripts/samples/train_connect4_alphazero_full.yaml scripts/train.yaml && python scripts/train.py
# Full training - Connect4 is harder than TicTacToe and requires more iterations

game: connect4

algorithm:
  name: alphazero
  device: mps

  model:
    class: Connect4MLPNet
    hidden: 256

  iterations: 800
  games_per_iteration: 50
  batch_size: 256
  train_steps_per_iteration: 400
  lr: 0.001
  weight_decay: 0.0001
  value_loss_coef: 1.0

  temp_moves: 12
  tau: 1.0
  deterministic_after_temp: true
  add_dirichlet_noise: true

  num_sims: 400
  c_puct: 1.5
  dirichlet_alpha: 0.3
  dirichlet_eps: 0.25
  illegal_action_penalty: 1000000000.0

  buffer_capacity: 200000
  clear_mcts_each_game: true
