# MCGS Training Configuration
game: connect4

algorithm:
  name: mcgs

  core:
    num_sims: 1000
    c_exploration: 1.414
    max_rollout_depth: 100
    max_nodes: 100000
    batch_size: 1

  trainer:
    num_test_games: 5
    random_seed: 42
    verbose: true
    device: cpu
